import os, sqlite3, pandas as pd

conn = sqlite3.connect('C:/Users/benim/revai/data/wf_intelligence.db')
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)
pd.set_option('display.float_format', '{:.2f}'.format)

output = []
SEP = '=' * 70

def run(name, sql):
    df = pd.read_sql_query(sql, conn)
    output.append(chr(10) + SEP + chr(10) + name + chr(10) + SEP)
    output.append(df.to_string(index=False))
    print(name, 'done -', len(df), 'rows')
    return df

run('Q1_CATEGORY_SUMMARY', "SELECT p.category,\n    COUNT(DISTINCT li.order_id) as order_count,\n    ROUND(SUM(li.line_total),2) as revenue,\n    ROUND(SUM(li.margin_amount),2) as total_margin,\n    ROUND(SUM(li.margin_amount)/SUM(li.line_total)*100,2) as margin_pct,\n    SUM(li.quantity) as units_sold,\n    ROUND(AVG(li.discount_pct),2) as avg_discount_pct\nFROM order_line_items li\nJOIN orders o ON li.order_id=o.order_id\nJOIN products p ON li.product_id=p.product_id\nWHERE o.status='Delivered'\nGROUP BY p.category ORDER BY revenue DESC")
run('Q2_TOP40_PRODUCTS_BY_REVENUE', "SELECT p.product_id, p.product_name, p.brand, p.category,\n    p.is_generic, ROUND(p.mrp,2) as mrp,\n    ROUND(p.margin_pct,2) as catalog_margin_pct,\n    COUNT(DISTINCT li.order_id) as order_count,\n    SUM(li.quantity) as units_sold,\n    ROUND(SUM(li.line_total),2) as revenue,\n    ROUND(SUM(li.margin_amount)/SUM(li.line_total)*100,2) as realized_margin_pct,\n    ROUND(AVG(li.discount_pct),2) as avg_discount_pct,\n    ROUND(SUM(li.margin_amount),2) as total_margin\nFROM order_line_items li\nJOIN orders o ON li.order_id=o.order_id\nJOIN products p ON li.product_id=p.product_id\nWHERE o.status='Delivered'\nGROUP BY p.product_id ORDER BY revenue DESC LIMIT 40")
run('Q3_STORE_PERFORMANCE', "SELECT s.store_id, s.store_name, s.city, s.store_type, s.size_sqft, s.online_enabled,\n    COUNT(DISTINCT o.order_id) as total_orders,\n    COUNT(DISTINCT CASE WHEN o.status='Delivered' THEN o.order_id END) as delivered,\n    COUNT(DISTINCT CASE WHEN o.status='Cancelled' THEN o.order_id END) as cancelled,\n    ROUND(COUNT(DISTINCT CASE WHEN o.status='Cancelled' THEN o.order_id END)*100.0/COUNT(DISTINCT o.order_id),2) as cancel_rate_pct,\n    ROUND(COUNT(DISTINCT CASE WHEN o.is_delayed=1 THEN o.order_id END)*100.0/NULLIF(COUNT(DISTINCT CASE WHEN o.channel='Online' AND o.status='Delivered' THEN o.order_id END),0),2) as online_delay_rate_pct,\n    ROUND(SUM(li.line_total),2) as revenue,\n    ROUND(SUM(li.margin_amount),2) as total_margin,\n    ROUND(SUM(li.margin_amount)/NULLIF(SUM(li.line_total),0)*100,2) as margin_pct\nFROM stores s\nLEFT JOIN orders o ON s.store_id=o.store_id\nLEFT JOIN order_line_items li ON o.order_id=li.order_id AND o.status='Delivered'\nGROUP BY s.store_id ORDER BY revenue DESC")
run('Q4_STORE_OOS_RATES', 'SELECT s.store_id, s.store_name, s.city,\n    COUNT(*) as sku_snapshots,\n    SUM(i.is_out_of_stock) as oos_count,\n    ROUND(AVG(i.is_out_of_stock)*100,2) as oos_rate_pct,\n    ROUND(AVG(i.days_out_of_stock),2) as avg_days_oos\nFROM inventory i\nJOIN stores s ON i.store_id=s.store_id\nGROUP BY i.store_id ORDER BY oos_rate_pct DESC')
run('Q5_CATEGORY_OOS_RATES', 'SELECT p.category,\n    COUNT(*) as sku_snapshots,\n    SUM(i.is_out_of_stock) as oos_count,\n    ROUND(AVG(i.is_out_of_stock)*100,2) as oos_rate_pct,\n    ROUND(AVG(i.days_out_of_stock),2) as avg_days_oos\nFROM inventory i\nJOIN products p ON i.product_id=p.product_id\nGROUP BY p.category ORDER BY oos_rate_pct DESC')
run('Q6_HIGH_MARGIN_HIGH_OOS_PRODUCTS', "SELECT p.product_id, p.product_name, p.category, p.brand, p.is_generic,\n    ROUND(p.mrp,2) as mrp, ROUND(p.margin_pct,2) as catalog_margin_pct,\n    COUNT(DISTINCT li.order_id) as order_count,\n    ROUND(SUM(li.line_total),2) as revenue,\n    ROUND(AVG(i.is_out_of_stock)*100,2) as oos_rate_pct,\n    ROUND(AVG(i.days_out_of_stock),2) as avg_days_oos\nFROM products p\nLEFT JOIN order_line_items li ON p.product_id=li.product_id\nLEFT JOIN orders o ON li.order_id=o.order_id AND o.status='Delivered'\nLEFT JOIN inventory i ON p.product_id=i.product_id\nGROUP BY p.product_id\nHAVING oos_rate_pct > 10 AND catalog_margin_pct > 25\nORDER BY catalog_margin_pct DESC, oos_rate_pct DESC\nLIMIT 40")
run('Q7_DISCOUNT_DRAG_MARGIN_EROSION', "SELECT p.product_id, p.product_name, p.category, p.brand,\n    ROUND(p.margin_pct,2) as catalog_margin_pct,\n    ROUND(AVG(li.discount_pct),2) as avg_discount_pct,\n    ROUND(SUM(li.margin_amount)/NULLIF(SUM(li.line_total),0)*100,2) as realized_margin_pct,\n    ROUND(p.margin_pct - SUM(li.margin_amount)/NULLIF(SUM(li.line_total),0)*100,2) as margin_erosion_pts,\n    ROUND(SUM(li.line_total),2) as revenue,\n    COUNT(DISTINCT li.order_id) as orders\nFROM order_line_items li\nJOIN orders o ON li.order_id=o.order_id\nJOIN products p ON li.product_id=p.product_id\nWHERE o.status='Delivered'\nGROUP BY p.product_id\nHAVING avg_discount_pct > 10 AND revenue > 3000\nORDER BY margin_erosion_pts DESC LIMIT 35")
run('Q8_CHANNEL_SPLIT_BY_CATEGORY', "SELECT p.category, o.channel,\n    COUNT(DISTINCT o.order_id) as orders,\n    ROUND(SUM(li.line_total),2) as revenue,\n    ROUND(SUM(li.margin_amount)/NULLIF(SUM(li.line_total),0)*100,2) as margin_pct,\n    ROUND(AVG(o.delivery_days),2) as avg_delivery_days\nFROM order_line_items li\nJOIN orders o ON li.order_id=o.order_id\nJOIN products p ON li.product_id=p.product_id\nWHERE o.status='Delivered'\nGROUP BY p.category, o.channel ORDER BY p.category, revenue DESC")
run('Q9_CANCELLATION_REASONS_BY_STORE', "SELECT s.store_name, s.city, o.channel, o.cancellation_reason,\n    COUNT(*) as cancel_count,\n    ROUND(COUNT(*)*100.0/(SELECT COUNT(*) FROM orders WHERE store_id=s.store_id),2) as pct_of_store_orders\nFROM orders o\nJOIN stores s ON o.store_id=s.store_id\nWHERE o.status='Cancelled' AND o.cancellation_reason IS NOT NULL AND o.cancellation_reason != ''\nGROUP BY s.store_id, o.channel, o.cancellation_reason\nORDER BY s.store_name, cancel_count DESC")
run('Q10_BASKET_CONTRIBUTION_GAP', "WITH total AS (\n    SELECT SUM(li.line_total) as total_rev, SUM(li.margin_amount) as total_margin\n    FROM order_line_items li JOIN orders o ON li.order_id=o.order_id WHERE o.status='Delivered'\n)\nSELECT p.product_name, p.category, p.brand,\n    ROUND(SUM(li.line_total),2) as revenue,\n    ROUND(SUM(li.line_total)*100.0/total_rev,3) as rev_share_pct,\n    ROUND(SUM(li.margin_amount),2) as margin,\n    ROUND(SUM(li.margin_amount)*100.0/total_margin,3) as margin_share_pct,\n    ROUND(SUM(li.margin_amount)/NULLIF(SUM(li.line_total),0)*100,2) as realized_margin_pct,\n    ROUND(SUM(li.margin_amount)*100.0/total_margin - SUM(li.line_total)*100.0/total_rev,3) as margin_vs_rev_gap\nFROM order_line_items li\nJOIN orders o ON li.order_id=o.order_id\nJOIN products p ON li.product_id=p.product_id\nCROSS JOIN total\nWHERE o.status='Delivered'\nGROUP BY p.product_id ORDER BY ABS(margin_vs_rev_gap) DESC LIMIT 30")
run('Q11_GENERIC_VS_BRANDED_BY_CATEGORY', "SELECT p.category,\n    CASE WHEN p.is_generic=1 THEN 'Generic' ELSE 'Branded' END as product_type,\n    COUNT(DISTINCT p.product_id) as sku_count,\n    ROUND(SUM(li.line_total),2) as revenue,\n    ROUND(SUM(li.margin_amount)/NULLIF(SUM(li.line_total),0)*100,2) as margin_pct,\n    SUM(li.quantity) as units_sold,\n    ROUND(AVG(i.is_out_of_stock)*100,2) as oos_rate_pct\nFROM products p\nLEFT JOIN order_line_items li ON p.product_id=li.product_id\nLEFT JOIN orders o ON li.order_id=o.order_id AND o.status='Delivered'\nLEFT JOIN inventory i ON p.product_id=i.product_id\nGROUP BY p.category, product_type ORDER BY p.category, revenue DESC")
run('Q12_HIGH_REVENUE_LOW_MARGIN_PRODUCTS', "SELECT p.product_id, p.product_name, p.category, p.brand,\n    ROUND(p.margin_pct,2) as catalog_margin_pct,\n    ROUND(SUM(li.margin_amount)/NULLIF(SUM(li.line_total),0)*100,2) as realized_margin_pct,\n    ROUND(SUM(li.line_total),2) as revenue,\n    COUNT(DISTINCT li.order_id) as orders,\n    ROUND(AVG(li.discount_pct),2) as avg_discount_pct\nFROM order_line_items li\nJOIN orders o ON li.order_id=o.order_id\nJOIN products p ON li.product_id=p.product_id\nWHERE o.status='Delivered'\nGROUP BY p.product_id\nHAVING revenue > 1000\nORDER BY realized_margin_pct ASC LIMIT 20")
run('Q13_STORE_CATEGORY_HEATMAP', "SELECT s.store_name, s.city, p.category,\n    ROUND(SUM(li.line_total),2) as revenue,\n    ROUND(SUM(li.margin_amount),2) as margin,\n    ROUND(SUM(li.margin_amount)/NULLIF(SUM(li.line_total),0)*100,2) as margin_pct,\n    COUNT(DISTINCT li.order_id) as orders\nFROM order_line_items li\nJOIN orders o ON li.order_id=o.order_id\nJOIN products p ON li.product_id=p.product_id\nJOIN stores s ON o.store_id=s.store_id\nWHERE o.status='Delivered'\nGROUP BY s.store_id, p.category ORDER BY s.store_name, revenue DESC")
run('Q14_OOS_BY_STORE_CATEGORY', 'SELECT s.store_name, s.city, p.category,\n    COUNT(*) as sku_snapshots,\n    SUM(i.is_out_of_stock) as oos_count,\n    ROUND(AVG(i.is_out_of_stock)*100,2) as oos_rate_pct,\n    ROUND(AVG(i.days_out_of_stock),2) as avg_days_oos\nFROM inventory i\nJOIN stores s ON i.store_id=s.store_id\nJOIN products p ON i.product_id=p.product_id\nGROUP BY i.store_id, p.category ORDER BY oos_rate_pct DESC')

conn.close()

out_path = 'C:/Users/benim/revai/analysis/mismatch_analysis.txt'
with open(out_path, 'w', encoding='utf-8') as f:
    f.write(chr(10).join(output))
print('DONE - saved to analysis/mismatch_analysis.txt')
print(f'File size: {os.path.getsize(out_path)} bytes')
section_count = len([x for x in output if x.strip().startswith('=')])
print(f'Total sections: {section_count}')
